CREATE TABLE DEMOTABLE
(
    ID       NUMERIC      NOT NULL,
    NAME     VARCHAR(255) NOT NULL,
    RECORDED TIMESTAMP    NOT NULL,
    CONSTRAINT table_pk PRIMARY KEY (ID)
);
CREATE TABLE DEMOPARTS
(
    ID   NUMERIC      NOT NULL,
    FK   NUMERIC      NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT parts_pk PRIMARY KEY (ID),
    CONSTRAINT parts_fk FOREIGN KEY (FK) REFERENCES DEMOTABLE (ID)
);

CREATE VIEW COMBINED_VIEW AS
    SELECT t1.ID, t1.NAME, Listagg(t2.NAME, ',') within GROUP (ORDER BY t2.ID) as parts
    FROM DEMOTABLE t1 LEFT JOIN DEMOPARTS t2 ON (t1.ID = t2.FK)
    GROUP BY t1.ID, t1.NAME;
